### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by curgery**
Officially requesting a change to this fabulous git tutorial.......

### CODE REVIEW

**Comment by hishamhm** [comment]
@curgery congrats on opening the PR! Did you push two empty files? (just checking to see if you did what you tried to do!)

**Comment by curgery** [comment]
Thanks, this information is much appreciated.....

**Comment by curgery** [comment]
Oops, i've made some sort of mistake.....have you accepted the merge?.........RLG

**Comment by hishamhm** [comment]
> have you accepted the merge?

No, I had not, because they were two zero-byte files, so I wanted to make sure you did that on purpose or if you were trying to send in a PR with some content.

**Comment by hishamhm** [comment]
But I did approve it now :) Congrats!

**Comment by curgery** [comment]
I really appreciate your response to my request, your work has been
instrumental in my progress as a new developer,
Thanks!
RL Glover

**Pull request merged**
